
##### NB's
```{r}
P2:
- Social (media) Big Data
- Network analysis for:
1 - Detecting populations (+ (overlapping) communities / clusters)
2 - Profiling
3 - Sentiment & topics - bias detection
4 - Finding influencers & propagation
```

##### General tools/stacks
```{r}


An iterative graph processing system built for high scalability:
("used at Facebook to analyze the social graph formed by users and their connections")
giraph.apache.org 

A Large-Scale Graph Processing System:
http://infolab.stanford.edu/gps/

Stanford Network Analysis Project:
http://snap.stanford.edu/

A a graph computing framework for both graph databases (OLTP) and graph analytic systems (OLAP):
http://tinkerpop.apache.org/


-> Gelly:
Gelly, Flink’s graph-processing API and library, 
native support for iterations makes it a suitable platform for large-scale graph analytics:
https://flink.apache.org/news/2015/08/24/introducing-flink-gelly.html

-> FLink:
http://data-artisans.com/robust-stream-processing-flink-walkthrough/

http://www.slideshare.net/sbaltagi/presentations
http://www.slideshare.net/sbaltagi/apacheflinkwhathowwhywhowherebyslimbaltagi-57825047
http://www.slideshare.net/sbaltagi/stepbystep-introduction-to-apache-flink

FlinkML: Large-scale Machine Learning with Apache Flink:
https://sics.app.box.com/s/044omad6200pchyh7ptbyxkwvcvaiowu



http://tvas.me/conferences/2016/09/01/KDD-2016-Highlights.html

http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=58111

Tidy text mining:
http://juliasilge.com/blog/Tidy-Text-Mining/

Network-metrics visualization:
http://kateto.net/network-visualization

http://kateto.net/polnet2016

https://snap.stanford.edu/data/index.html
http://followthehashtag.com/datasets/

(Topology: http://twitter.mpi-sws.org/)
(other network related data: http://theodi.fbk.eu/openbigdata/#portfolioModal11
-> possibly interesting: use tele-communications dataset for making day-time population models)

Streaming:
www.slideshare.net/HuafengWang/functional-comparison-and-performance-evaluation-of-streaming-frameworks 
Benchmark:
https://github.com/intel-hadoop/HiBench

```



##### 1 - Populations ((overlapping) community/cluster detection)
```{r}

Overlapping & non-overlapping clusters/communities

K-clique algorithm:
(+ mixed-membership stochastic block models, Airoldi et al. -> prodability distribution
of community memberships, for every pair of communities you know the background linking probability for that pair)

Discovering communities:
1 - take dataset, 2 - represent as graph, 3 - identify communities (or clusters), 4 - interpret clusters as real communities. 
Look at ground-truth, true latent clusters
Find networks with labels for clusters ahead of time:
Scientific collaborations: journals as research areas
Social networks: groups, lists
Information networks: topic based groups
A node can be a member of 0 or more group
[…]

"Guaranteed Learning of Latent Variable Models: Overlapping Community Models and Overcomplete Representations

Incorporating latent or hidden variables is a crucial aspect of statistical modeling. 
I will present a statistical and a computational framework for guaranteed learning of a wide range of latent variable models. 
I will focus on two instances, viz., community detection and overcomplete representations.
The goal of community detection is to discover hidden communities from graph data. 
I will present a tensor decomposition approach for learning probabilistic mixed membership models. 
The tensor approach is guaranteed to correctly recover the mixed membership communities with tight guarantees. 
We have deployed it on many real-world networks, e.g. Facebook, Yelp and DBLP. 
It is easily parallelizable, and is orders of magnitude faster than the state-of-art stochastic variational approach."

https://www.youtube.com/watch?v=7BKsmmxDq6Y


+

Mining Large Graphs:
http://slideplayer.com/slide/4741541/

```

##### 2 - Profiling
```{r}

Part of entity resolution, collective classification, and to a degree link prediction:
https://www.youtube.com/watch?v=-sccHBewf5Q
https://www.youtube.com/watch?v=fEY0MUC8ND0
https://www.youtube.com/watch?v=YsQEg6OroiQ

http://infolab.stanford.edu/serf/


```

##### 3 - Sentiment & topics: bias discovery
```{r}

Data/examples:
https://www.kaggle.com/crowdflower/twitter-airline-sentiment
https://www.kaggle.com/benhamner/d/crowdflower/twitter-airline-sentiment/
exploring-airline-twitter-sentiment-data

NLP + ML:

Tensorflow:
https://explosion.ai/blog/syntaxnet-in-context
jrmeyer.github.io/tutorial/2016/02/01/TensorFlow-Tutorial.html (!)

Tensorflow + CNN's
http://www.wildml.com/2015/12/implementing-a-cnn-for-text-classification-in-tensorflow/

Tensorflow + RNN's
http://cs224d.stanford.edu/assignment2/

Tensorflow + binary classification:
http://jrmeyer.github.io/tutorial/2016/02/01/TensorFlow-Tutorial.html

-- Hybrid: 
Rule-based + statistical methods:
http://dataconomy.com/ai-language-understanding/

Text mining/NLP/Sentiment analysis:
Prof. Bing Liu
https://www.youtube.com/watch?v=6ki_F_5a5vg
https://www.cs.uic.edu/~liub/teach/cs583-fall-16/cs583.html
https://www.cs.uic.edu/~liub/IJCAI15-tutorial.html
(217 slides, on LML)
www.cs.uic.edu/~liub/Lifelong-Machine-Learning-Tutorial-KDD-2016.pdf
https://www.cs.uic.edu/~liub/lifelong-learning.html
https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html

http://ssix-project.eu/
https://www.youtube.com/watch?v=Ccm2avJPnDQ

NLP:
http://www.kdnuggets.com/2016/06/inside-update-natural-language-processing.html

Topic modeling:
http://www.kdnuggets.com/2016/07/americas-next-topic-model.html

Sentiment:
http://www.kdnuggets.com/2016/10/emotion-analytics-why-important.html
http://www.kdnuggets.com/2016/07/mining-twitter-data-python-part-6.html
http://www.kdnuggets.com/2016/09/slangsd-sentiment-dictionary-slang-words.html
http://www.kdnuggets.com/2016/09/trump-phenomenon-twitter-based-recount.html
http://www.kdnuggets.com/2015/10/aspect-based-sentiment-analysis-competition.html

```

##### 4 - Influencers & propagation
```{r}

Data/examples:
http://blog.kaggle.com/2016/06/03/dataset-spotlight-how-isis-uses-twitter/
https://snap.stanford.edu/data/higgs-twitter.html


Test idea:
- grab 5-10 of biggest* news providers (NL) in twitter
- grab 1-2 neutral/fact based news providers (cbs/? see: e.g. www.pewresearch.org/fact-tank/ 
  + https://twitter.com/FactTank)
- measure:
-- tweet frequency
-- followers
-- number of retweets
-- sentiment (general)
-- topic bias (1 - proportion of specific topics mentioned / not mentioned, 
   2 - bias in sentiment towards topiccs)
-- propagation (1 - centrality measures, 2 - reach, 3 - membership of ammount of clusters)



```



